.TH "ITAKA" "1" 
.SH "NAME" 
itaka \(em On-demand screenshooting server 
.SH "SYNOPSIS" 
.PP 
\fBitaka\fR 
.SH "DESCRIPTION" 
.PP 
Itaka is a on-demand screenshooting server based on the HTTP protocol. It integrates a specifically coded server to take screenshots on-demand when your machine is queried through a remote browser. It has a GTK GUI for client notification. 
.SH OPTIONS
Itaka follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.TP
.B \-r, \-\-revision
Show the revision of program.
.TP
.B \-d, \-\-debug
Start in debug mode.
.SH "SEE ALSO" 
.PP 
README file in source or on Debian systems: /usr/share/doc/itaka/README.gz
.SH "AUTHOR" 
.PP 
Itaka was written by: Marc E. <santusmarc@users.sf.net>
.PP 
This manual page was written by Marc E. <santusmarc@users.sourceforge.net> for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
.\" created by instant / docbook-to-man, Tue 05 Jun 2007, 21:05 
